# -*- coding: utf-8 -*-
"""AIAC-14

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RFWp5p5j7CJ__Qi1PPjGzrS-wxffWEoT

### **Task 1 – Portfolio Website Design**
"""

from IPython.display import display, HTML

html = """
<!DOCTYPE html>
<html>
<head>

<style>

body{
font-family: Arial;
margin:0;
scroll-behavior:smooth;
}

nav{
background:#1e3a8a;
padding:15px;
position:fixed;
width:100%;
}

nav a{
color:white;
margin:15px;
text-decoration:none;
font-weight:bold;
}

section{
padding:100px 40px;
height:100vh;
}

.projects{
display:grid;
grid-template-columns:repeat(auto-fit,minmax(200px,1fr));
gap:20px;
}

.card{
background:#f4f4f4;
padding:20px;
border-radius:8px;
}

</style>
</head>

<body>

<nav>
<a href="#about">About</a>
<a href="#projects">Projects</a>
<a href="#contact">Contact</a>
</nav>

<section id="about">
<h2>About Me</h2>
<p>I am a web developer building modern websites.</p>
</section>

<section id="projects">
<h2>Projects</h2>

<div class="projects">
<div class="card">Project 1</div>
<div class="card">Project 2</div>
<div class="card">Project 3</div>
</div>

</section>

<section id="contact">
<h2>Contact</h2>
<p>Email : example@gmail.com</p>
</section>

</body>
</html>
"""

display(HTML(html))

"""### **Task 2 – Online Store Product Page**"""

from IPython.display import display, HTML

html = """

<style>

.product{
text-align:center;
font-family:Arial;
max-width:300px;
margin:auto;
}

.product__img{
width:100%;
}

.product__btn{
background:#28a745;
color:white;
padding:10px 20px;
border:none;
cursor:pointer;
}

.product__btn:hover{
background:#1e7e34;
}

</style>

<script>

function addCart(){
alert("Product added to cart!")
}

</script>

<div class="product">

<img class="product__img"
src="https://via.placeholder.com/300">

<h2 class="product__title">Smart Watch</h2>

<p class="product__price">$120</p>

<button class="product__btn"
onclick="addCart()">Add to Cart</button>

</div>
"""

display(HTML(html))

"""### **Task 3 – Event Registration Form**"""

from IPython.display import display, HTML

html = """

<style>

form{
width:300px;
margin:auto;
font-family:Arial;
}

input,select{
width:100%;
padding:10px;
margin:10px 0;
}

button{
background:#007bff;
color:white;
padding:10px;
border:none;
}

</style>

<script>

function validateForm(){

let name=document.forms["form"]["name"].value

if(name==""){
alert("Name must be filled")
return false
}

return true
}

</script>

<h2 align=center>Event Registration</h2>

<form name="form" onsubmit="return validateForm()">

<label>Name</label>
<input type="text" name="name">

<label>Email</label>
<input type="email">

<label>Phone</label>
<input type="tel">

<label>Session</label>

<select>
<option>AI</option>
<option>Web Development</option>
<option>Cyber Security</option>
</select>

<button type="submit">Register</button>

</form>
"""

display(HTML(html))

"""### **Task 4 – Resume Website**"""

from IPython.display import display, HTML

html = """

<style>

body{
font-family:Georgia;
scroll-behavior:smooth;
}

nav{
background:#333;
padding:10px;
}

nav a{
color:white;
margin:10px;
text-decoration:none;
}

.container{
display:grid;
grid-template-columns:1fr;
gap:30px;
padding:40px;
}

section{
border-bottom:1px solid #ddd;
padding:20px;
}

</style>

<nav>

<a href="#profile">Profile</a>
<a href="#skills">Skills</a>
<a href="#education">Education</a>
<a href="#experience">Experience</a>

</nav>

<div class="container">

<section id="profile">
<h2>Profile Summary</h2>
<p>Motivated software developer.</p>
</section>

<section id="skills">
<h2>Skills</h2>
<p>Python, HTML, CSS, JavaScript</p>
</section>

<section id="education">
<h2>Education</h2>
<p>B.Tech Computer Science</p>
</section>

<section id="experience">
<h2>Experience</h2>
<p>Web Developer Intern</p>
</section>

</div>
"""

display(HTML(html))

"""### **Task 5 – Restaurant Menu Page**"""

from IPython.display import display, HTML

html = """

<style>

body{
font-family:Arial;
background:#fff8f0;
}

.menu{
display:grid;
grid-template-columns:repeat(auto-fit,minmax(200px,1fr));
gap:20px;
padding:40px;
}

.card{
background:white;
padding:20px;
border-radius:10px;
box-shadow:0 3px 6px rgba(0,0,0,0.2);
transition:0.3s;
}

.card:hover{
transform:scale(1.05);
}

.price{
color:#e63946;
font-weight:bold;
}

</style>

<h1 align=center>Restaurant Menu</h1>

<div class="menu">

<div class="card">
<h3>Pizza</h3>
<p>Cheese pizza</p>
<p class="price">$10</p>
</div>

<div class="card">
<h3>Burger</h3>
<p>Chicken burger</p>
<p class="price">$8</p>
</div>

<div class="card">
<h3>Pasta</h3>
<p>Italian pasta</p>
<p class="price">$12</p>
</div>

</div>

"""

display(HTML(html))