# -*- coding: utf-8 -*-
"""AIAC-17

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iKPpY2-C0i9ltSWbTW1asDrde9e11pOI

# **Lab 17 – AI for Data Processing: Data Cleaning and Preprocessing Scripts**

### **Task 1 – Customer Data Cleaning**
"""

import pandas as pd

data=pd.DataFrame({
'age':[25,None,30],
'income':[50000,60000,None],
'city':['Delhi','Mumbai','Delhi'],
'gender':['Male','Female','Male']
})

print("Before:\n",data)

data['age'].fillna(data['age'].mean(),inplace=True)
data['income'].fillna(data['income'].median(),inplace=True)
data['city']=data['city'].str.lower()

data=pd.get_dummies(data,columns=['gender','city'])

print("\nAfter:\n",data)

"""### **Task 2 – Sales Data Preprocessing**"""

import pandas as pd

data=pd.DataFrame({
'date':['2023-01-01','2023-01-02'],
'sales':[200,300]
})

print("Before:\n",data)

data['date']=pd.to_datetime(data['date'])

data['month']=data['date'].dt.month
data['year']=data['date'].dt.year
data['day']=data['date'].dt.day_name()

data['sales']=(data['sales']-data['sales'].min())/(data['sales'].max()-data['sales'].min())

print("\nAfter:\n",data)

"""### **Task 3 – Healthcare Data Preparation**"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder,MinMaxScaler

data=pd.DataFrame({
'blood_pressure':[120,None],
'cholesterol':[200,180],
'gender':['Male','Female']
})

print("Before:\n",data)

data.fillna(data.mean(numeric_only=True),inplace=True)

le=LabelEncoder()
for col in data.select_dtypes(include='object'):
    data[col]=le.fit_transform(data[col])

scaler=MinMaxScaler()
num=data.select_dtypes(include='number').columns
data[num]=scaler.fit_transform(data[num])

print("\nAfter:\n",data)

"""### **Task 4 – Employee Salary Data Preprocessing**"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder

data=pd.DataFrame({
'salary':[30000,None],
'department':['HR','IT'],
'location':['Delhi','Mumbai']
})

print("Before:\n",data)

data.fillna(method='ffill',inplace=True)

data['department']=data['department'].str.lower()

le=LabelEncoder()
data['department']=le.fit_transform(data['department'])
data['location']=le.fit_transform(data['location'])

print("\nAfter:\n",data)